### ISSUE TITLE
Ведущему непонятно откуда ему загружать вопросы для игры

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#1]
Шаги:
1. Открываем приложение **HostApp.exe**
2. Нажимаем на кнопку **Загрузить игру**
3. По умолчанию открывается последняя папка, из которой мы загружали вопросы, либо открывается папка **Документы**. Из-за этого пользователю приходится искать папку, в которой находится нужный ему вопрос

_Ожидалось_: Откроется папка **Вопросы**, в которой можно будет открыть необходимый набор вопросов.

**Comment by taler0n** [comment]
Вопросы ведущий делает сам, поэтому папки "Вопросы" нет. Куда сохранял, там и будет искать

**Comment by YarComicSans** [comment]
А если пользователь будет играть не на своем компе/не будет хорошо обращаться с ним? Мне кажется, что все таки лучше было бы открывать сразу в папке с вопросами. И обязать создателя вопросов их туда и сохранять.

**Comment by taler0n** [comment]
Папки с вопросами не существует. Как минимум, пока не существует конструктора игр

**Comment by taler0n** [comment]
Исправлено. Теперь по умолчанию предлагается сохранять/загружать в ту же папку, где экзешник.
