### ISSUE TITLE
Нет ограничения на длину имени игрока

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#11]
Если ввести достаточно длинное имя в поле **Введите имя игрока**, то оно обрежется и полностью выводиться не будет на протяжении всей игры

![default](https://user-images.githubusercontent.com/41051182/50445332-24599e80-091f-11e9-9e35-34ec5140ef2d.png)

![default](https://user-images.githubusercontent.com/41051182/50445336-291e5280-091f-11e9-9895-32c6cab5eb32.png)

**Comment by taler0n** [comment]
Исправлено
