### ISSUE TITLE
Не сразу понятен смысл кнопки Выйти в окне с вопросом

### ISSUE THREAD

**Issue by IrinaGribkova** [taler0n/jeopardy#12]
При окончании ответа всех участников нам нужно вернуться к таблице вопросов, у нас остаётся кнопка Выйти. Но непонятно, выйти из игры или просто вернуться к таблице вопросов.
Лучше переименовать кнопку Выйти в Кнопку Вернуться к таблице вопросов.
![1](https://user-images.githubusercontent.com/43450202/50445416-a5189a80-091f-11e9-987f-618535617781.jpg)

**Comment by taler0n** [comment]
Исправлено
