### ISSUE TITLE
При исключении из сессии игры игрок не видит об этом оповещения, остается в игре

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#13]
1. Открываем HostApp.exe, выбираем список вопросов и ждем подключения трех игроков
2. Открываем три окна PlayerApp.exe. В первом окне нажимаем Соединение, вводим IP, который выводится на экран в HostApp.exe, 192.168.79.1, вводим имя пользователя 2 и нажимаем Соединение.
![default](https://user-images.githubusercontent.com/41051182/50445504-4e5f9080-0920-11e9-9d40-5c9a9da33cda.png)
3. В окне ведущего выбираем игрока **2** и нажимаем исключить
![default](https://user-images.githubusercontent.com/41051182/50445508-57e8f880-0920-11e9-9682-8df32a0eef09.png)

Игрок не может понять, что его отключили от сессии игры.
Ожидалось: Игрока отсоединят и ему нужно будет подключиться заново. И игрок увидит оповещение о том, что его отключили от сессии

**Comment by taler0n** [comment]
Исправлено
