### ISSUE TITLE
При повторном подключении к игре можно начать игру с 1 игроком

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#14]
1. Открываем 1 приложение **PlayerApp.exe**, подключаемся к игре с именем пользователя **1**
2. В этом же окне нажимаем **Соединение** и подключаемся к игре с именем пользователя **1.1**
3. В этом же окне нажимаем **Соединение** и подключаемся к игре с именем пользователя **1.1.1**
4. В окне ведущего нажимаем на **Начать игру**

![default](https://user-images.githubusercontent.com/41051182/50445943-160d8180-0923-11e9-967b-b5e05652b29f.png)

5. Игра запустилась

![default](https://user-images.githubusercontent.com/41051182/50445951-23c30700-0923-11e9-9b51-f7d19993139a.png)

Ожидалось: Игра запуститься только когда 3 игрока подключены к игре

**Comment by taler0n** [comment]
Исправлено
