### ISSUE TITLE
При проигрыше в раунде игрока, выбиравшего вопрос, на другом окне с таблицей вопросов, право выбирать всё равно остаётся у него

### ISSUE THREAD

**Issue by IrinaGribkova** [taler0n/jeopardy#16]
1. Открываем окно с ведущим.
2. Открываем три окна с игроками: Ирина, Даня, Ваня.
3. Ирина выбирает первый вопрос за 300. Проигрывает. Но на другом окне она всё равно имет право выбрать вопрос.
![default](https://user-images.githubusercontent.com/43450202/50448818-63461f00-0934-11e9-88c2-5f55fa7d837a.jpg)

**Comment by taler0n** [comment]
В начале раунда право выбирать вопрос - у игрока с наименьшим счетом. После вопроса - у ответившего верно. Такие правила игры. А окошко следующего раунда открываться не должно, это сейчас фиксится.

P.S.  Думаю даже написать все правила в текстовый файлик и положить в репо, чтобы таких вопросов не было.
