### ISSUE TITLE
Удаление пользователей при повторном подключении игрока к игре

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#3]
Шаги:
1. Открываем **HostApp.exe**, выбираем список вопросов и ждем подключения трех игроков
2. Открываем три окна **PlayerApp.exe**. В первом окне нажимаем **Соединение**, вводим IP, который выводится на экран в **HostApp.exe**, **192.168.79.1**, вводим имя пользователя **1** и нажимаем **Соединение**. Дальше повторяем эти же действия. имя пользователя введем как **1.2**
3. Далее в двух других окнах подключаем игроков с именами **2** и **3**

![default](https://user-images.githubusercontent.com/41051182/50443933-a42f3b00-0916-11e9-9181-67184b4a4853.png)

4. Игру начать нельзя. По всей видимости, для этого нам нужно чтобы было только 3 игрока. Удалим **3**, выделив его и нажав на кнопку *Исключить*. Далее нажимаем на **Начать игру**
5. Игрок **1** остался среди играющих.
![default](https://user-images.githubusercontent.com/41051182/50443992-e8bad680-0916-11e9-8be4-3b4772817b7b.png)

Ожидается: При переподключении игрока его старое имя удаляется из списка игроков. Так будет ограничена возможность совершения ведущим ошибки, описанной выше.

**Comment by taler0n** [comment]
Исправлено
