### ISSUE TITLE
Непонятен смысл кнопки Редактировать

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#4]
При нажатии кнопки **Редактировать** начинается какая-то магия. 
1) Можно нажимать на вопросы и удалять их из общего списка вопросов (При этом нужно на каждый вопрос нажать, потом выбрать **Правильный ответ**, **Выйти**, и только после этого вопрос удаляется.
2) При выполнении пункта 1), а так же при нажатии на кнопку **Сохранить изменения** открываются дополнительные окна, насколько я понял, со следующими раундами

![default](https://user-images.githubusercontent.com/41051182/50444222-6206f900-0918-11e9-92d1-85919ab0f804.png)

Ожидалось: Кнопка **Редактировать** позволяет динамически менять набор вопросов\ счет прямо во время раунда

**Comment by taler0n** [comment]
Ошибка есть, но она не совсем в этом. При открытии вопроса возникает окошко следующего раунда. Кнопка "Редактировать" позволяет менять счет или пропускать раунд. Она работает корректно.

**Comment by taler0n** [comment]
Исправлено.
