### ISSUE TITLE
При многократном нажатии игрока на кнопку Ответить у ведущего в окне отображается имя игрока столько раз, сколько он нажал на кнопку Ответить

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#5]
1. Открываем **HostApp.exe**, выбираем список вопросов и ждем подключения трех игроков
2. Открываем три окна **PlayerApp.exe**. В первом окне нажимаем Соединение, вводим IP, который   выводится на экран в **HostApp.exe**, 192.168.79.1, вводим имя пользователя 1 и нажимаем Соединение. Далее в двух других окнах подключаем игроков с именами 2 и 3
3. Нажимаем на кнопку **Начать игру**
4. Выбираем любой вопрос. Нажимаем в окне игрока **3** несколько раз кнопку **Ответ**
5. В окне ведущего в поле **Отвечает** игрок **3** появился несколько раз

![default](https://user-images.githubusercontent.com/41051182/50444755-4c470300-091b-11e9-842d-b4e56ce473d9.png)

Ожидалось: Игрок **3** появится только 1 раз

**Comment by taler0n** [comment]
Исправлено
