### ISSUE TITLE
Игроки могут отвечать на вопросы даже после того как на этот вопрос был дан правильный ответ

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#6]
1. Открываем HostApp.exe, выбираем список вопросов и ждем подключения трех игроков
 2. Открываем три окна PlayerApp.exe. В первом окне нажимаем Соединение, вводим IP, который выводится на экран в HostApp.exe, 192.168.79.1, вводим имя пользователя 1 и нажимаем Соединение. Далее в двух других окнах подключаем игроков с именами 2 и 3
 3. Нажимаем на кнопку Начать игру
 4. Выбираем любой вопрос. Нажимаем на кнопку **Ответ** у игрока **3**, **2** и **1**
 5. Нажимаем на кнопку **Верно** в окне ведущего
 6. Нажимаем на кнопку **Ответ** у любого игрока. Кнопки **Верно** и **Неверно** появляются снова. Более того, за правильный\неправильный ответ все еще будут добавляться\вычитаться баллы у игроков.

![default](https://user-images.githubusercontent.com/41051182/50445085-43efc780-091d-11e9-839d-8ad12017aa8d.png)

![default](https://user-images.githubusercontent.com/41051182/50445028-e6f41180-091c-11e9-908a-5d013603d22e.png)

Ожидалось: После ответа на вопрос игрок больше не может давать ответ и получать за это очки или терять их

**Comment by taler0n** [comment]
Исправлено
