### ISSUE TITLE
При нажатии на поля Введите IP и Введите имя содержимое полей удаляется

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#7]
При нажатии на кнопки **Введите IP** и **Введите имя** содержимое полей удаляется. В случае необходимости пользователю исправить одно из полей ему придется вводить его заново

![default](https://user-images.githubusercontent.com/41051182/50445171-e1e39200-091d-11e9-820a-674ea5d7cdf6.png)

![default](https://user-images.githubusercontent.com/41051182/50445173-e740dc80-091d-11e9-8813-04f220ce83e7.png)

**Comment by taler0n** [comment]
Фича
