### ISSUE TITLE
Очередь из отвечающих на вопрос не удаляется при многократном нажатии на кнопу ответить у нескольких участников

### ISSUE THREAD

**Issue by IrinaGribkova** [taler0n/jeopardy#8]
1. Открываем HostApp.exe, выбираем список вопросов и ждем подключения трех игроков
2. Открываем три окна PlayerApp.exe. В первом окне нажимаем Соединение, вводим IP, который выводится на экран в HostApp.exe, 169.254.177.133, вводим имя пользователя Ирина и нажимаем Соединение. Далее в двух других окнах подключаем игроков с именами Ваня и Даня.
3. Нажимаем на кнопку Начать игру
Выбираем любой вопрос. Нажимаем в окне игрока Ирина несколько раз кнопку Ответ, Затем в Окне Даня, затем в окне Ваня.
![default](https://user-images.githubusercontent.com/43450202/50445155-c24c6980-091d-11e9-9e3f-35781ec58e95.png)
5. Нажимаем на Кнопку Верно. Из очереди отвечающих исчезает только первое имя, а сами кнопки Верно и Неверно пропадают.
![default](https://user-images.githubusercontent.com/43450202/50445212-1d7e5c00-091e-11e9-8a1c-d48946c0dc3e.jpg)
Ожидаемой поведение: в очереди не повторяются имена участников и после первого правильного ответа список из отвечающих очищается.

**Comment by taler0n** [comment]
Исправлено
