### ISSUE TITLE
При вводе неправильного IP программа аварийно прекращает свою работу

### ISSUE THREAD

**Issue by YarComicSans** [taler0n/jeopardy#9]
Если пользователь вводит неправильный IP адрес и нажимает на кнопку **Соединение**, то нет никакой подсказки о том, что была совершена ошибка. Более того, программа аварийно завершает свою работу
![default](https://user-images.githubusercontent.com/41051182/50445237-469eec80-091e-11e9-9ca8-3ad164b70753.png)

**Comment by taler0n** [comment]
Исправлено
